# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title
relative_permalinks: true

# Setup
title:            "Stephen E Lane"
tagline:          "Thoughts etc."
description:      "Couldn't think of anything witty to write &#12483"
url:              http://www.stephenelane.com
baseurl:          /

author:
  name:           "Stephen Lane"
  url:            https://twitter.com/stephenelane

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SteveLane

twitter_username: stephenelane
github_username: SteveLane
