name : Stephen E Lane
brand : Stephen E Lane
description : Couldn't think of anything witty to write &#12483
keyword : 
url:              https://SteveLane.github.io
baseurl:          /
# email : 
twitter : stephenelane
github : SteveLane
author : Stephen E Lane
analytics : UA-56563625-1
year : 2017
# markdown : kramdown
  
exclude :
  - node_modules
  - NonPostFiles

paginate:         5
paginate_path: "/blog/page:num"
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title
